# Inserts a blank line between shell prompts
add_newline = true

# Customizing the prompt
format = """
$username\
$hostname\
$shlvl\
$singularity\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$deno\
$golang\
$lua\
$nodejs\
$python\
$rust\
$memory_usage\
$gcloud\
$openstack\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
[$character](bold green)"""

# Display arrow character
[character] # The name of the module we are configuring is "character"

error_symbol = "[➜](bold red)" 
success_symbol = "[➜](bold green)"

# Configure if and how the time is shown
[time]
disabled = false
time_format = "%T"
format = "[$time ](bold blue)"

[sudo]
disabled = false
style = "bold green"
symbol = "💪"
format = "[<SUDO>$symbol]($style)"

[status]
disabled = false
style = "bg:blue"
symbol = "🔴"
map_symbol = true
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '

