import = ['~/.config/alacritty/colors.toml']

[env]
TERM = 'xterm-256color'

[window]
blur = false
padding = { x = 10, y = 10 }
opacity = 0.90
decorations = "Buttonless"
dimensions = { columns = 110, lines = 52 }
startup_mode = 'Windowed'
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[font]

normal = { family = "IosevkaNerd Font", style = "SemiBold" }
bold = { family = "IosevkaNerd Font", style = "Bold" }

size = 18
